# test/test_gamlss_vs_rgamlss.jl
#
# Compare GAM.jl's gamlss() against R's gamlss package reference values.
# Reference data are generated by test/r_comparison/gamlss_vs_rgamlss.R.
#
# R gamlss uses pb() P-spline smooths with local ML / GAIC smoothing
# parameter selection.  GAM.jl's :ps basis is the equivalent of R's pb()
# (both are B-spline + difference penalty).
#
# Three SP selection strategies are tested:
#   - EFS (Extended Fellner-Schall) vs R pb(method="ML"):  different
#     algorithms targeting the same ML-type criterion; gives the closest
#     match (cor > 0.999 for both μ and σ).
#   - local_gaic vs R pb(method="GAIC"):  both use AIC-based grid search;
#     typically matches well.
#   - local_ml vs R pb(method="ML"):  now uses the same parameter-scale
#     working responses/weights as R gamlss for the local smoother update,
#     so it should match closely as well.
#
# To regenerate:
#   cd GAM.jl && Rscript test/r_comparison/gamlss_vs_rgamlss.R

using Test
using GAM
using CSV, DataFrames, Statistics

const REFDIR_RG = joinpath(@__DIR__, "r_comparison")

# Skip the entire file when reference data is missing.
if !isfile(joinpath(REFDIR_RG, "gamlss_rgamlss_no_data.csv"))
    @warn "Skipping GAMLSS vs R-gamlss tests — reference CSVs not found. " *
          "Run:  Rscript test/r_comparison/gamlss_vs_rgamlss.R"
else

# ─── helpers ─────────────────────────────────────────────────────────
"""Per-smooth EDF for parameter `k` in a `MultiParameterModel`."""
function smooth_edfs_rg(m, k::Int)
    edfs = Float64[]
    for sm in m.smooths[k]
        push!(edfs, sum(m.edf[sm.first_para:sm.last_para]))
    end
    return edfs
end

"""Read a single-row summary CSV and return it as a NamedTuple."""
function read_summary_rg(path)
    df = CSV.read(path, DataFrame)
    return (; (Symbol(n) => df[1, n] for n in names(df))...)
end

"""Check fitted values and summary stats against R gamlss reference."""
function check_gamlss_vs_rgamlss(m, ref_fit, ref_sum;
                                  mu_link_inv = identity,
                                  sigma_link_inv = exp,
                                  cor_mu_thresh = 0.99,
                                  cor_sigma_thresh = 0.90,
                                  nll_reltol = 0.10)
    μ_julia = mu_link_inv.(m.fitted_eta[1])
    σ_julia = sigma_link_inv.(m.fitted_eta[2])
    μ_r     = ref_fit.mu_fitted
    σ_r     = ref_fit.sigma_fitted

    cor_mu = cor(μ_julia, μ_r)
    cor_sigma = cor(σ_julia, σ_r)
    nll_rel = abs(m.nll - ref_sum.nll) / abs(ref_sum.nll)

    @test cor_mu    > cor_mu_thresh
    @test cor_sigma > cor_sigma_thresh
    @test nll_rel   < nll_reltol
end

# ════════════════════════════════════════════════════════════════════════
@testset "GAMLSS vs R-gamlss" begin
# ════════════════════════════════════════════════════════════════════════

# ───────────────────────────────────────────────────────────────────────
# Normal location-scale (NO)
#   R gamlss NO:  identity(mu), log(sigma)
#   GAM.jl GaussianLS:  IdentityLink(mu), LogLink(sigma)
# ───────────────────────────────────────────────────────────────────────
@testset "GaussianLS (NO)" begin
    data = CSV.read(joinpath(REFDIR_RG, "gamlss_rgamlss_no_data.csv"), DataFrame)

    # pb(x, inter=20, degree=3) → 23 basis;  pb(x, inter=8, degree=3) → 11 basis
    f_mu    = @formulak(y ~ s(x, k = 23, bs = :ps))
    f_sigma = @formulak(y ~ s(x, k = 11, bs = :ps))

    @testset "RS + EFS vs pb(method=ML)" begin
        ref_fit = CSV.read(joinpath(REFDIR_RG, "gamlss_rgamlss_no_fitted.csv"), DataFrame)
        ref_sum = read_summary_rg(joinpath(REFDIR_RG, "gamlss_rgamlss_no_summary.csv"))

        ctrl = GAM.gamlss_control(sp_method = :efs, n_cyc = 50, trace = false)
        m = gamlss([f_mu, f_sigma], data, GaussianLS();
                   method = :rs, gamlss_ctrl = ctrl)

        @test m.converged
        check_gamlss_vs_rgamlss(m, ref_fit, ref_sum;
                                 mu_link_inv = identity, sigma_link_inv = exp,
                                 cor_mu_thresh = 0.999, cor_sigma_thresh = 0.999,
                                 nll_reltol = 0.01)
    end

    @testset "RS + local_ml vs pb(method=ML)" begin
        ref_fit = CSV.read(joinpath(REFDIR_RG, "gamlss_rgamlss_no_fitted.csv"), DataFrame)
        ref_sum = read_summary_rg(joinpath(REFDIR_RG, "gamlss_rgamlss_no_summary.csv"))

        ctrl = GAM.gamlss_control(sp_method = :local_ml, n_cyc = 50, trace = false)
        m = gamlss([f_mu, f_sigma], data, GaussianLS();
                   method = :rs, gamlss_ctrl = ctrl)

        @test m.converged
        check_gamlss_vs_rgamlss(m, ref_fit, ref_sum;
                                 mu_link_inv = identity, sigma_link_inv = exp,
                                 cor_mu_thresh = 0.999, cor_sigma_thresh = 0.999,
                                 nll_reltol = 0.01)
    end

    @testset "RS + local_gaic vs pb(method=GAIC)" begin
        ref_fit = CSV.read(joinpath(REFDIR_RG, "gamlss_rgamlss_no_gaic_fitted.csv"), DataFrame)
        ref_sum = read_summary_rg(joinpath(REFDIR_RG, "gamlss_rgamlss_no_gaic_summary.csv"))

        ctrl = GAM.gamlss_control(sp_method = :local_gaic, gaic_k = 2.0,
                                  n_cyc = 50, trace = false)
        m = gamlss([f_mu, f_sigma], data, GaussianLS();
                   method = :rs, gamlss_ctrl = ctrl)

        @test m.converged
        check_gamlss_vs_rgamlss(m, ref_fit, ref_sum;
                                 mu_link_inv = identity, sigma_link_inv = exp,
                                 cor_mu_thresh = 0.99, cor_sigma_thresh = 0.90,
                                 nll_reltol = 0.10)
    end
end

# ───────────────────────────────────────────────────────────────────────
# Gamma location-scale (GA)
#   R gamlss GA:  log(mu), log(sigma)  where sigma = CV
#   GAM.jl GammaLocationScale:  LogLink(mu), LogLink(sigma)
# ───────────────────────────────────────────────────────────────────────
@testset "GammaLS (GA)" begin
    data = CSV.read(joinpath(REFDIR_RG, "gamlss_rgamlss_ga_data.csv"), DataFrame)

    f_mu    = @formulak(y ~ s(x, k = 23, bs = :ps))
    f_sigma = @formulak(y ~ s(x, k = 11, bs = :ps))

    @testset "RS + EFS vs pb(method=ML)" begin
        ref_fit = CSV.read(joinpath(REFDIR_RG, "gamlss_rgamlss_ga_fitted.csv"), DataFrame)
        ref_sum = read_summary_rg(joinpath(REFDIR_RG, "gamlss_rgamlss_ga_summary.csv"))

        ctrl = GAM.gamlss_control(sp_method = :efs, n_cyc = 50, trace = false)
        m = gamlss([f_mu, f_sigma], data, GammaLS();
                   method = :rs, gamlss_ctrl = ctrl)

        @test m.converged
        check_gamlss_vs_rgamlss(m, ref_fit, ref_sum;
                                 mu_link_inv = exp, sigma_link_inv = exp,
                                 cor_mu_thresh = 0.999, cor_sigma_thresh = 0.999,
                                 nll_reltol = 0.01)
    end

    @testset "RS + local_ml vs pb(method=ML)" begin
        ref_fit = CSV.read(joinpath(REFDIR_RG, "gamlss_rgamlss_ga_fitted.csv"), DataFrame)
        ref_sum = read_summary_rg(joinpath(REFDIR_RG, "gamlss_rgamlss_ga_summary.csv"))

        ctrl = GAM.gamlss_control(sp_method = :local_ml, n_cyc = 50, trace = false)
        m = gamlss([f_mu, f_sigma], data, GammaLS();
                   method = :rs, gamlss_ctrl = ctrl)

        @test m.converged
        check_gamlss_vs_rgamlss(m, ref_fit, ref_sum;
                                 mu_link_inv = exp, sigma_link_inv = exp,
                                 cor_mu_thresh = 0.999, cor_sigma_thresh = 0.999,
                                 nll_reltol = 0.01)
    end

    @testset "RS + local_gaic vs pb(method=GAIC)" begin
        ref_fit = CSV.read(joinpath(REFDIR_RG, "gamlss_rgamlss_ga_gaic_fitted.csv"), DataFrame)
        ref_sum = read_summary_rg(joinpath(REFDIR_RG, "gamlss_rgamlss_ga_gaic_summary.csv"))

        ctrl = GAM.gamlss_control(sp_method = :local_gaic, gaic_k = 2.0,
                                  n_cyc = 50, trace = false)
        m = gamlss([f_mu, f_sigma], data, GammaLS();
                   method = :rs, gamlss_ctrl = ctrl)

        @test m.converged
        check_gamlss_vs_rgamlss(m, ref_fit, ref_sum;
                                 mu_link_inv = exp, sigma_link_inv = exp,
                                 cor_mu_thresh = 0.99, cor_sigma_thresh = 0.90,
                                 nll_reltol = 0.10)
    end
end

end  # @testset "GAMLSS vs R-gamlss"
end  # if reference data exists
