# R comparison tests for SPDE smooth
#
# Compares Julia SPDE smooth against pre-generated R reference data.
# Reference data in test/r_comparison/ was generated by spde_comparison.R.
#
# Since the R SPDE smooth uses INLA's mesh/FEM, the underlying mesh is
# different from our evenly-spaced mesh, so we compare against:
# 1. R's TP smooth (both should recover the true function)
# 2. R's SPDE fitted values (if INLA data available) — correlation check

using Test
using GAM
using DataFrames
using CSV
using LinearAlgebra
using Statistics
using StatsAPI: fitted, coef

@testset "SPDE R comparison" begin
    # Load R reference data
    data_path = joinpath(@__DIR__, "r_comparison", "spde_data.csv")
    tp_path = joinpath(@__DIR__, "r_comparison", "spde_tp_fitted.csv")

    dat = CSV.read(data_path, DataFrame)
    r_tp = CSV.read(tp_path, DataFrame)

    n = nrow(dat)
    f_true = sin.(dat.x)

    @testset "Julia SPDE vs R TP baseline: both recover sin(x)" begin
        m = gam(@formulak(y ~ s(x, bs = :spde, k = 30)), dat)

        @test m.converged

        # R's TP correlation with true function
        r2_r_tp = cor(r_tp.fitted, f_true)^2

        # Julia SPDE correlation with true function
        r2_jl_spde = cor(fitted(m), f_true)^2

        # Both should recover the function well
        @test r2_r_tp > 0.85
        @test r2_jl_spde > 0.75

        # Julia SPDE fitted should be reasonably correlated with R TP fitted
        # (they use different bases but fit the same smooth function)
        @test cor(fitted(m), r_tp.fitted)^2 > 0.85
    end

    # Check against R SPDE if data is available
    spde_path = joinpath(@__DIR__, "r_comparison", "spde_spde_fitted.csv")
    if isfile(spde_path)
        r_spde = CSV.read(spde_path, DataFrame)

        @testset "Julia SPDE vs R SPDE (INLA): fitted value correlation" begin
            m = gam(@formulak(y ~ s(x, bs = :spde, k = 30)), dat)

            # The mesh construction differs (INLA uses degree-2 splines on a
            # different mesh), so exact match is not expected.  But both should
            # recover the same underlying function.
            r2_fits = cor(fitted(m), r_spde.fitted)^2
            @test r2_fits > 0.85

            # Both should correlate well with the true function
            @test cor(r_spde.fitted, f_true)^2 > 0.85
            @test cor(fitted(m), f_true)^2 > 0.75
        end
    end
end
