# test/test_gamlss_vs_mgcv.jl
#
# Compare GAM.jl's gamlss() against mgcv's gaulss/gammals reference values.
# Reference data are generated by test/r_comparison/gamlss_vs_mgcv.R.
#
# To regenerate:
#   cd GAM.jl && Rscript test/r_comparison/gamlss_vs_mgcv.R

using Test
using GAM
using CSV, DataFrames, Statistics

const REFDIR = joinpath(@__DIR__, "r_comparison")

# Skip the entire file when reference data is missing.
if !isfile(joinpath(REFDIR, "gamlss_gaulss_data.csv"))
    @warn "Skipping GAMLSS vs mgcv tests — reference CSVs not found. " *
          "Run:  Rscript test/r_comparison/gamlss_vs_mgcv.R"
else

# ─── helpers ─────────────────────────────────────────────────────────
"""Per-smooth EDF for parameter `k` in a `MultiParameterModel`."""
function smooth_edfs(m, k::Int)
    edfs = Float64[]
    for sm in m.smooths[k]
        push!(edfs, sum(m.edf[sm.first_para:sm.last_para]))
    end
    return edfs
end

"""Read a single-row summary CSV and return it as a NamedTuple."""
function read_summary(path)
    df = CSV.read(path, DataFrame)
    return (; (Symbol(n) => df[1, n] for n in names(df))...)
end

"""Check fitted values and summary stats against mgcv reference."""
function check_gamlss_vs_ref(m, ref_fit, ref_sum;
                              mu_link_inv = identity,
                              sigma_link_inv = exp,
                              cor_mu_thresh = 0.99,
                              cor_sigma_thresh = 0.95,
                              nll_reltol = 0.05,
                              edf_reltol = 0.20)
    μ_julia = mu_link_inv.(m.fitted_eta[1])
    σ_julia = sigma_link_inv.(m.fitted_eta[2])
    μ_r     = ref_fit.mu_fitted
    σ_r     = ref_fit.sigma_fitted

    @test cor(μ_julia, μ_r)  > cor_mu_thresh
    @test cor(σ_julia, σ_r)  > cor_sigma_thresh

    @test abs(m.nll - ref_sum.nll) / abs(ref_sum.nll) < nll_reltol

    edf_mu    = smooth_edfs(m, 1)
    edf_sigma = smooth_edfs(m, 2)
    @test length(edf_mu)    == 1
    @test length(edf_sigma) == 1
    @test abs(edf_mu[1]    - ref_sum.edf_mu)    / max(ref_sum.edf_mu,    1.0) < edf_reltol
    @test abs(edf_sigma[1] - ref_sum.edf_sigma) / max(ref_sum.edf_sigma, 1.0) < edf_reltol
end

# ════════════════════════════════════════════════════════════════════════
@testset "GAMLSS vs mgcv" begin
# ════════════════════════════════════════════════════════════════════════

# ───────────────────────────────────────────────────────────────────────
# Gaussian location-scale  (gaulss)
#   GaussianLS: IdentityLink for μ, LogLink for σ
#   mgcv gaulss: identity for μ, logb for τ=1/σ
# ───────────────────────────────────────────────────────────────────────
@testset "GaussianLS (gaulss)" begin
    data = CSV.read(joinpath(REFDIR, "gamlss_gaulss_data.csv"), DataFrame)

    @testset "bs=cr" begin
        ref_fit = CSV.read(joinpath(REFDIR, "gamlss_gaulss_cr_fitted.csv"), DataFrame)
        ref_sum = read_summary(joinpath(REFDIR, "gamlss_gaulss_cr_summary.csv"))

        m = gamlss(
            [@formulak(y ~ s(x, k = 20, bs = :cr)),
             @formulak(y ~ s(x, k = 10, bs = :cr))],
            data, GaussianLS(); method = :efs)

        @test m.converged
        check_gamlss_vs_ref(m, ref_fit, ref_sum;
                            mu_link_inv = identity, sigma_link_inv = exp)
    end

    @testset "bs=tp" begin
        ref_fit = CSV.read(joinpath(REFDIR, "gamlss_gaulss_tp_fitted.csv"), DataFrame)
        ref_sum = read_summary(joinpath(REFDIR, "gamlss_gaulss_tp_summary.csv"))

        m = gamlss(
            [@formulak(y ~ s(x, k = 20, bs = :tp)),
             @formulak(y ~ s(x, k = 10, bs = :tp))],
            data, GaussianLS(); method = :efs)

        @test m.converged
        check_gamlss_vs_ref(m, ref_fit, ref_sum;
                            mu_link_inv = identity, sigma_link_inv = exp)
    end
end

# ───────────────────────────────────────────────────────────────────────
# Gamma location-scale  (gammals)
#   GammaLS (= GammaLocationScale): LogLink for μ, LogLink for σ (CV)
#   mgcv gammals: identity on log(μ), identity on log(φ)
#   Relationship: φ = σ² ⇒ σ = √φ  (R script saves σ = √φ)
# ───────────────────────────────────────────────────────────────────────
@testset "GammaLS (gammals)" begin
    data = CSV.read(joinpath(REFDIR, "gamlss_gammals_data.csv"), DataFrame)

    @testset "bs=cr" begin
        ref_fit = CSV.read(joinpath(REFDIR, "gamlss_gammals_cr_fitted.csv"), DataFrame)
        ref_sum = read_summary(joinpath(REFDIR, "gamlss_gammals_cr_summary.csv"))

        m = gamlss(
            [@formulak(y ~ s(x, k = 20, bs = :cr)),
             @formulak(y ~ s(x, k = 10, bs = :cr))],
            data, GammaLS(); method = :efs)

        @test m.converged
        check_gamlss_vs_ref(m, ref_fit, ref_sum;
                            mu_link_inv = exp, sigma_link_inv = exp)
    end

    @testset "bs=tp" begin
        ref_fit = CSV.read(joinpath(REFDIR, "gamlss_gammals_tp_fitted.csv"), DataFrame)
        ref_sum = read_summary(joinpath(REFDIR, "gamlss_gammals_tp_summary.csv"))

        m = gamlss(
            [@formulak(y ~ s(x, k = 20, bs = :tp)),
             @formulak(y ~ s(x, k = 10, bs = :tp))],
            data, GammaLS(); method = :efs)

        @test m.converged
        check_gamlss_vs_ref(m, ref_fit, ref_sum;
                            mu_link_inv = exp, sigma_link_inv = exp)
    end
end

end  # @testset "GAMLSS vs mgcv"
end  # if reference data exists
