{
  "hash": "c50938aa12a1d9cd4e95b9e97fe62003",
  "result": {
    "engine": "julia",
    "markdown": "---\ntitle: \"Non-Gaussian Response Distributions\"\nauthor: \"Simon Frost\"\nformat:\n  html:\n    code-fold: false\n    toc: true\n  gfm:\n    toc: true\n  pdf:\n    toc: true\nengine: julia\n---\n\n## Overview\n\nGAMs are not limited to Gaussian responses. By specifying a **family** (distribution) and **link function**, we can model count data, binary outcomes, positive continuous data, and more. The general model is:\n\n$$\ng(\\mu_i) = \\beta_0 + f_1(x_{1i}) + \\cdots + f_p(x_{pi}), \\quad y_i \\sim \\text{Family}(\\mu_i, \\phi)\n$$\n\nThis vignette demonstrates three common non-Gaussian families:\n\n| Family | Link | Response type | Example |\n|--------|------|---------------|---------|\n| Poisson | log | Counts | Species counts, event rates |\n| Binomial | logit | Binary / proportions | Presence–absence, disease status |\n| Gamma | inverse (or log) | Positive continuous | Waiting times, claim sizes |\n\nThe second half of the vignette turns to a setting where the choice of family\ndoes real work: **disease incidence counts**. There we add an *offset* to model\nrates rather than raw counts, and then deal with **overdispersion** — count data\nmore variable than the Poisson distribution permits — using three further\nfamilies:\n\n| Family | Variance | Estimates |\n|--------|----------|-----------|\n| `NegBinFamily` | $\\mu + \\mu^2/\\theta$ | $\\theta$ |\n| `QuasiPoissonFamily` | $\\phi\\mu$ | $\\phi$ |\n| `TweedieFamily` | $\\phi\\mu^p$ | $\\phi$, optionally $p$ |\n\n## Setup\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nusing GAM\nusing CSV\nusing StatsAPI: residuals, fitted, r2, deviance, coef, coeftable, aic,\n    predict, dof_residual\nusing Statistics: mean, var\nusing GLM: LogLink, LogitLink\n\nusing DataFrames\nusing Plots\nusing Distributions\n```\n:::\n\n\n\n## Poisson GAM — count data\n\n### Simulating count data\n\nWe simulate counts from a Poisson distribution with a smooth log-rate:\n\n$$\ny_i \\sim \\text{Poisson}(\\mu_i), \\quad \\log(\\mu_i) = 1 + 1.5 \\sin(2\\pi x_i)\n$$\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ndf_pois = CSV.read(\"data_poisson.csv\", DataFrame)\nx = df_pois.x\nn = nrow(df_pois)\nη = 1.0 .+ 1.5 .* sin.(2π .* x)\nord = sortperm(x)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n300-element Vector{Int64}:\n   1\n   2\n   3\n   4\n   5\n   6\n   7\n   8\n   9\n  10\n   ⋮\n 292\n 293\n 294\n 295\n 296\n 297\n 298\n 299\n 300\n```\n:::\n:::\n\n\n\n### Fitting the model\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nm_pois = gam(@formula(y ~ s(x, k = 15, bs = :cr)), df_pois;\n    family = Poisson(), link = LogLink())\nm_pois\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nGeneralized Additive Model\n\nFormula: y ~ 1 + s(x,bs=cr)\n\nFamily: Poisson\nLink:   LogLink\nMethod: REML\n\nParametric coefficients:\n──────────────────────────────────────────────────\n                Coef.  Std. Error      z  Pr(>|z|)\n──────────────────────────────────────────────────\n(Intercept)  0.939669   0.0468399  20.06    <1e-88\n──────────────────────────────────────────────────\n\nApproximate significance of smooth terms:\n──────────────────────────────────────────────────────────────────\nSmooth                    edf   Ref.df     Chi.sq    p-value     \n──────────────────────────────────────────────────────────────────\ns(x,bs=cr)               7.98     9.60    667.413 7.395e-139 *** \n──────────────────────────────────────────────────────────────────\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nR² (adj) = 0.764   Deviance explained = 76.4%\n-REML = 566.9   n = 300\n```\n:::\n:::\n\n\n\n### Smooth estimate\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nse_pois = smooth_estimates(m_pois; n = 200)\nx_grid = se_pois.covariates[:x]\n\np1 = plot(x_grid, se_pois.estimate;\n    ribbon = 2 .* se_pois.se,\n    fillalpha = 0.2,\n    label = \"s(x) ± 2SE\",\n    linewidth = 2,\n    xlabel = \"x\",\n    ylabel = \"f(x) [log scale]\",\n    title = \"Poisson GAM — smooth on link scale\")\nplot!(p1, x[ord], (η .- mean(η))[ord];\n    label = \"true f(x)\",\n    linestyle = :dash,\n    linewidth = 2,\n    color = :red)\np1\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](04_families_files/figure-commonmark/cell-5-output-1.svg){}\n:::\n:::\n\n\n\n### Deviance residuals\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nresid_pois = residuals(m_pois; type = :deviance)\n\np2 = scatter(fitted(m_pois), resid_pois;\n    xlabel = \"Fitted values\",\n    ylabel = \"Deviance residuals\",\n    title = \"Poisson GAM — residuals\",\n    alpha = 0.4,\n    markersize = 3,\n    label = false)\nhline!(p2, [0]; linestyle = :dash, color = :gray, label = false)\np2\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](04_families_files/figure-commonmark/cell-6-output-1.svg){}\n:::\n:::\n\n\n\n## Binomial GAM — binary data\n\n### Simulating binary data\n\nWe simulate binary outcomes from a logistic model:\n\n$$\ny_i \\sim \\text{Bernoulli}(p_i), \\quad \\text{logit}(p_i) = -0.5 + 2\\sin(2\\pi x_i)\n$$\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ndf_bin = CSV.read(\"data_binomial.csv\", DataFrame)\nx_bin = df_bin.x\nη_bin = -0.5 .+ 2.0 .* sin.(2π .* x_bin)\nord_bin = sortperm(x_bin)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n300-element Vector{Int64}:\n   1\n   2\n   3\n   4\n   5\n   6\n   7\n   8\n   9\n  10\n   ⋮\n 292\n 293\n 294\n 295\n 296\n 297\n 298\n 299\n 300\n```\n:::\n:::\n\n\n\n### Fitting the model\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nm_bin = gam(@formula(y ~ s(x, k = 15, bs = :cr)), df_bin;\n    family = Binomial(), link = LogitLink())\nm_bin\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nGeneralized Additive Model\n\nFormula: y ~ 1 + s(x,bs=cr)\n\nFamily: Binomial\nLink:   LogitLink\nMethod: REML\n\nParametric coefficients:\n───────────────────────────────────────────────────\n                 Coef.  Std. Error      z  Pr(>|z|)\n───────────────────────────────────────────────────\n(Intercept)  -0.857991    0.159647  -5.37    <1e-07\n───────────────────────────────────────────────────\n\nApproximate significance of smooth terms:\n──────────────────────────────────────────────────────────────────\nSmooth                    edf   Ref.df     Chi.sq    p-value     \n──────────────────────────────────────────────────────────────────\ns(x,bs=cr)               4.98     6.15     68.652  1.955e-13 *** \n──────────────────────────────────────────────────────────────────\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nR² (adj) = 0.295   Deviance explained = 25.5%\n-REML = 153   n = 300\n```\n:::\n:::\n\n\n\n### Smooth estimate\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nse_bin = smooth_estimates(m_bin; n = 200)\nx_grid_bin = se_bin.covariates[:x]\n\np3 = plot(x_grid_bin, se_bin.estimate;\n    ribbon = 2 .* se_bin.se,\n    fillalpha = 0.2,\n    label = \"s(x) ± 2SE\",\n    linewidth = 2,\n    xlabel = \"x\",\n    ylabel = \"f(x) [logit scale]\",\n    title = \"Binomial GAM — smooth on link scale\")\nplot!(p3, x_bin[ord_bin], (η_bin .- mean(η_bin))[ord_bin];\n    label = \"true f(x)\",\n    linestyle = :dash,\n    linewidth = 2,\n    color = :red)\np3\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](04_families_files/figure-commonmark/cell-9-output-1.svg){}\n:::\n:::\n\n\n\n### Deviance residuals\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nresid_bin = residuals(m_bin; type = :deviance)\n\np4 = scatter(fitted(m_bin), resid_bin;\n    xlabel = \"Fitted values (probability)\",\n    ylabel = \"Deviance residuals\",\n    title = \"Binomial GAM — residuals\",\n    alpha = 0.4,\n    markersize = 3,\n    label = false)\nhline!(p4, [0]; linestyle = :dash, color = :gray, label = false)\np4\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](04_families_files/figure-commonmark/cell-10-output-1.svg){}\n:::\n:::\n\n\n\n## Gamma GAM — positive continuous data\n\n### Simulating positive continuous data\n\nWe simulate positive continuous data from a Gamma distribution with a smooth log-mean:\n\n$$\ny_i \\sim \\text{Gamma}(\\text{shape}, \\text{scale}_i), \\quad \\log(\\mu_i) = 1 + \\sin(2\\pi x_i)\n$$\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ndf_gam = CSV.read(\"data_gamma.csv\", DataFrame)\nx_gam = df_gam.x\nη_gam = 1.0 .+ sin.(2π .* x_gam)\nord_gam = sortperm(x_gam)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n300-element Vector{Int64}:\n   1\n   2\n   3\n   4\n   5\n   6\n   7\n   8\n   9\n  10\n   ⋮\n 292\n 293\n 294\n 295\n 296\n 297\n 298\n 299\n 300\n```\n:::\n:::\n\n\n\n### Fitting the model\n\nWe use `Gamma()` with `LogLink()` (log link is more commonly used in practice than the canonical inverse link):\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nm_gam = gam(@formula(y ~ s(x, k = 15, bs = :cr)), df_gam;\n    family = Gamma(), link = LogLink())\nm_gam\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nGeneralized Additive Model\n\nFormula: y ~ 1 + s(x,bs=cr)\n\nFamily: Gamma\nLink:   LogLink\nMethod: REML\n\nParametric coefficients:\n─────────────────────────────────────────────────\n               Coef.  Std. Error      t  Pr(>|t|)\n─────────────────────────────────────────────────\n(Intercept)  1.02615   0.0245722  41.76    <1e-99\n─────────────────────────────────────────────────\n\nApproximate significance of smooth terms:\n──────────────────────────────────────────────────────────────────\nSmooth                    edf   Ref.df          F    p-value     \n──────────────────────────────────────────────────────────────────\ns(x,bs=cr)               6.18     7.59     32.876  1.407e-33 *** \n──────────────────────────────────────────────────────────────────\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nR² (adj) = 0.362   Deviance explained = 41.5%\n-REML = 474   Scale est. = 0.1811   n = 300\n```\n:::\n:::\n\n\n\n### Smooth estimate\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nse_gam = smooth_estimates(m_gam; n = 200)\nx_grid_gam = se_gam.covariates[:x]\n\np5 = plot(x_grid_gam, se_gam.estimate;\n    ribbon = 2 .* se_gam.se,\n    fillalpha = 0.2,\n    label = \"s(x) ± 2SE\",\n    linewidth = 2,\n    xlabel = \"x\",\n    ylabel = \"f(x) [log scale]\",\n    title = \"Gamma GAM — smooth on link scale\")\nplot!(p5, x_gam[ord_gam], (η_gam .- mean(η_gam))[ord_gam];\n    label = \"true f(x)\",\n    linestyle = :dash,\n    linewidth = 2,\n    color = :red)\np5\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](04_families_files/figure-commonmark/cell-13-output-1.svg){}\n:::\n:::\n\n\n\n### Deviance residuals\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nresid_gam = residuals(m_gam; type = :deviance)\n\np6 = scatter(fitted(m_gam), resid_gam;\n    xlabel = \"Fitted values\",\n    ylabel = \"Deviance residuals\",\n    title = \"Gamma GAM — residuals\",\n    alpha = 0.4,\n    markersize = 3,\n    label = false)\nhline!(p6, [0]; linestyle = :dash, color = :gray, label = false)\np6\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](04_families_files/figure-commonmark/cell-14-output-1.svg){}\n:::\n:::\n\n\n\n## Disease incidence — offsets and exposure\n\nThe Poisson model above treats every observation as equally \"exposed\": each row\ncontributes one count drawn from a rate that depends only on `x`. Epidemiological\ncount data rarely look like that. A district with 40,000 residents will record\nmore cases than one with 1,500 at the *same* underlying risk, simply because more\npeople are at risk. What we want to model is the **rate**, not the raw count.\n\nThe standard device is an **offset**: a term added to the linear predictor with a\nknown coefficient fixed at 1. Writing $E_i$ for the population at risk,\n\n$$\ny_i \\sim \\text{Poisson}(\\mu_i), \\quad\n\\log(\\mu_i) = \\underbrace{\\log(E_i)}_{\\text{offset}} + \\beta_0 + f(x_i)\n$$\n\nRearranging shows what the smooth now means:\n\n$$\n\\log\\!\\left(\\frac{\\mu_i}{E_i}\\right) = \\beta_0 + f(x_i)\n$$\n\nso $\\beta_0 + f(x)$ is the log **incidence rate**, and the count scale is carried\nentirely by the offset.\n\n### Simulated district-week counts\n\nWe simulate 400 district-weeks. Populations are lognormal, and the log-rate\nvaries smoothly with an environmental index $x$:\n\n$$\n\\log(\\text{pop}_i) \\sim N(9,\\, 0.7^2), \\qquad\n\\log(\\mu_i) = \\log(\\text{pop}_i) - 6.0 + 0.9\\sin(2\\pi x_i)\n$$\n\nThe baseline rate $e^{-6} \\approx 2.5$ cases per 1,000 is modulated by\n$e^{\\pm 0.9}$, so the rate at the seasonal peak is $e^{1.8} \\approx 6$ times the\nrate at the trough.\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ndf_inc = CSV.read(\"data_incidence.csv\", DataFrame)\nfirst(df_inc, 4)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>4×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">x</th><th style = \"text-align: left;\">pop</th><th style = \"text-align: left;\">y</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">0.771154</td><td style = \"text-align: right;\">6213.0</td><td style = \"text-align: right;\">6.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">0.489192</td><td style = \"text-align: right;\">11983.0</td><td style = \"text-align: right;\">36.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">0.506597</td><td style = \"text-align: right;\">5689.0</td><td style = \"text-align: right;\">14.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">0.721246</td><td style = \"text-align: right;\">5769.0</td><td style = \"text-align: right;\">6.0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nextrema(df_inc.pop), extrema(df_inc.y)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n((1283.0, 46255.0), (1.0, 198.0))\n```\n:::\n:::\n\n\n\nPopulations span more than an order of magnitude, so the raw counts are\ndominated by population size rather than by risk.\n\n### Fitting with an offset\n\nThe offset is a **keyword argument**, not a formula term (see the migration\nvignette — mgcv's in-formula `offset(log(E))` has no equivalent here):\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nm_inc = gam(@formula(y ~ s(x, k = 12, bs = :cr)), df_inc;\n    family = Poisson(), link = LogLink(),\n    offset = log.(df_inc.pop))\nm_inc\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nGeneralized Additive Model\n\nFormula: y ~ 1 + s(x,bs=cr)\n\nFamily: Poisson\nLink:   LogLink\nMethod: REML\n\nParametric coefficients:\n────────────────────────────────────────────────────\n                Coef.  Std. Error        z  Pr(>|z|)\n────────────────────────────────────────────────────\n(Intercept)  -5.95213   0.0105925  -561.92    <1e-99\n────────────────────────────────────────────────────\n\nApproximate significance of smooth terms:\n──────────────────────────────────────────────────────────────────\nSmooth                    edf   Ref.df     Chi.sq    p-value     \n──────────────────────────────────────────────────────────────────\ns(x,bs=cr)               9.11    10.24   3815.810          0 *** \n──────────────────────────────────────────────────────────────────\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nR² (adj) = 0.974   Deviance explained = 92.4%\n-REML = 1188   n = 400\n```\n:::\n:::\n\n\n\nThe intercept estimates the mean log-rate:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nprintln(\"intercept = \", round(coef(m_inc)[1], digits = 4), \"   (simulated: -6.0)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nintercept = -5.9521   (simulated: -6.0)\n```\n:::\n:::\n\n\n\nand the Pearson dispersion statistic, $X^2 / (n - \\text{edf})$, is close to 1 as\nit should be when a Poisson model is correctly specified:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ndisp_inc = sum(residuals(m_inc; type = :pearson) .^ 2) / dof_residual(m_inc)\nprintln(\"Pearson dispersion = \", round(disp_inc, digits = 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPearson dispersion = 0.949\n```\n:::\n:::\n\n\n\n### Why not just model the rate directly?\n\nTwo shortcuts suggest themselves, and both are worse than the offset.\n\n**Shortcut 1: use $\\log(\\text{pop})$ as an ordinary covariate.** This estimates\nthe coefficient rather than fixing it at 1:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ndf_inc.log_pop = log.(df_inc.pop)\nm_cov = gam(@formula(y ~ log_pop + s(x, k = 12, bs = :cr)), df_inc;\n    family = Poisson(), link = LogLink())\n\nb_lp = coef(m_cov)[2]\nse_lp = coeftable(m_cov).cols[2][2]\nprintln(\"log(pop) coefficient = \", round(b_lp, digits = 4),\n        \"  (95% CI \", round(b_lp - 1.96se_lp, digits = 4), \", \",\n        round(b_lp + 1.96se_lp, digits = 4), \")\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nlog(pop) coefficient = 0.9946  (95% CI 0.9688, 1.0205)\n```\n:::\n:::\n\n\n\nHere the estimate is 0.995 with a confidence interval comfortably covering 1, so\nthe data are perfectly consistent with proportionality — which is reassuring, but\nis not the point. The offset model *imposes* the proportionality we know to hold\nby construction, spends no degree of freedom estimating it, and yields an\nintercept and smooth that are directly interpretable as a log-rate. The\ncovariate model spends a parameter re-learning a known constant, and if that\nestimate had drifted from 1 the smooth would silently absorb the difference.\n\n**Shortcut 2: model $y/\\text{pop}$ as a Gaussian response.** This throws away the\ncount nature of the data entirely:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ndf_inc.rate = df_inc.y ./ df_inc.pop\nm_rate = gam(@formula(rate ~ s(x, k = 12, bs = :cr)), df_inc)\nprintln(\"Gaussian-on-rate edf = \", round(sum(edf(m_rate)), digits = 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nGaussian-on-rate edf = 9.386\n```\n:::\n:::\n\n\n\nThe fit runs, but the variance model is wrong in a way that matters: a rate\ncomputed from 1,500 residents is far noisier than one from 40,000, and a Gaussian\nmodel with constant variance gives them equal weight. Poisson-with-offset gets\nthis right automatically, because the variance of a count is its mean, which\nscales with exposure.\n\n### Recovering the rate curve\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nse_inc = smooth_estimates(m_inc; n = 200)\nxg = se_inc.covariates[:x]\ntruth_inc = 0.9 .* sin.(2π .* xg)\n\np_inc = plot(xg, se_inc.estimate .- mean(se_inc.estimate);\n    ribbon = 2 .* se_inc.se, fillalpha = 0.2,\n    label = \"ŝ(x) ± 2SE\", linewidth = 2,\n    xlabel = \"environmental index x\", ylabel = \"log incidence rate (centred)\",\n    title = \"Poisson GAM with log-population offset\")\nplot!(p_inc, xg, truth_inc .- mean(truth_inc);\n    label = \"true f(x)\", linestyle = :dash, linewidth = 2, color = :red)\np_inc\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](04_families_files/figure-commonmark/cell-22-output-1.svg){}\n:::\n:::\n\n\n\n### Prediction requires the offset again\n\nAn offset is part of the model, so predictions on new data need one. GAM.jl\ntakes it as a keyword to `predict`, exactly as mgcv requires new-data offsets:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nnd = DataFrame(x = [0.25, 0.75])\npred_10k = predict(m_inc, nd; type = :response, offset = fill(log(10_000.0), 2))\n\nprintln(\"expected weekly cases in a district of 10,000:\")\nprintln(\"  peak season  (x = 0.25): \", round(pred_10k[1], digits = 1))\nprintln(\"  trough       (x = 0.75): \", round(pred_10k[2], digits = 1))\nprintln(\"  ratio = \", round(pred_10k[1] / pred_10k[2], digits = 2),\n        \"   (simulated: \", round(exp(1.8), digits = 2), \")\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nexpected weekly cases in a district of 10,000:\n  peak season  (x = 0.25): 59.5\n  trough       (x = 0.75): 9.7\n  ratio = 6.13   (simulated: 6.05)\n```\n:::\n:::\n\n\n\n::: {.callout-warning}\nIf you omit `offset=` at prediction time it is treated as zero — that is,\na population of $e^0 = 1$ — and the predictions come back on a meaningless\nscale rather than raising an error. Always pass the new-data offset.\n:::\n\n## Overdispersion in count data\n\nReal count data are usually more variable than the Poisson distribution allows.\nPoisson forces $\\text{Var}(y) = \\mu$; unmodelled heterogeneity, clustering of\ncases within households, or a missing covariate all inflate the variance beyond\nthat. The consequence is not mainly bias in $\\hat{f}$ — it is badly understated\nuncertainty.\n\nWe simulate weekly counts at a single surveillance site (constant population, so\nno offset is needed) with genuine extra-Poisson variation:\n\n$$\ny_i \\sim \\text{NegBin}(\\mu_i, \\theta), \\quad\n\\log(\\mu_i) = 2.5 + 0.9\\sin(2\\pi x_i), \\quad \\theta = 2,\n$$\n\nfor which $\\text{Var}(y) = \\mu + \\mu^2/\\theta$.\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ndf_od = CSV.read(\"data_incidence_od.csv\", DataFrame)\nprintln(\"mean = \", round(mean(df_od.y), digits = 2),\n        \"   variance = \", round(var(df_od.y), digits = 1),\n        \"   zeros = \", count(==(0), df_od.y))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmean = 13.8   variance = 235.3   zeros = 15\n```\n:::\n:::\n\n\n\n### Detecting overdispersion\n\nFit the Poisson model and look at the dispersion statistic:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nf_od = @formula(y ~ s(x, k = 12, bs = :cr))\nm_od_pois = gam(f_od, df_od; family = Poisson(), link = LogLink())\n\ndisp_od = sum(residuals(m_od_pois; type = :pearson) .^ 2) / dof_residual(m_od_pois)\nprintln(\"Pearson dispersion = \", round(disp_od, digits = 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPearson dispersion = 8.66\n```\n:::\n:::\n\n\n\nA value near 1 is consistent with Poisson variation; 8.7 is not. (Compare the\n0.95 obtained for the correctly-specified offset model above — that contrast is\nwhat the statistic is for.)\n\n### Three principled responses\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nm_od_nb = gam(f_od, df_od; family = NegBinFamily(), link = LogLink())\nprintln(\"NegBin θ̂ = \", round(m_od_nb.family.theta, digits = 3), \"   (simulated: 2.0)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNegBin θ̂ = 1.992   (simulated: 2.0)\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nm_od_qp = gam(f_od, df_od; family = QuasiPoissonFamily(), link = LogLink())\nprintln(\"quasi-Poisson scale = \", round(m_od_qp.scale, digits = 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nquasi-Poisson scale = 8.613\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nm_od_tw = gam(f_od, df_od;\n    family = TweedieFamily(; p = 1.5, estimate_p = true), link = LogLink())\nprintln(\"Tweedie p̂ = \", round(m_od_tw.family.p, digits = 3),\n        \"   scale = \", round(m_od_tw.scale, digits = 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTweedie p̂ = 1.544   scale = 1.945\n```\n:::\n:::\n\n\n\nThe negative binomial recovers $\\theta$ essentially exactly, and the\nquasi-Poisson dispersion lands on the same value as the Pearson statistic — as it\nmust, since that is how it is estimated.\n\n| Family | Variance | Estimates | Use when |\n|---|---|---|---|\n| `NegBinFamily()` | $\\mu + \\mu^2/\\theta$ | $\\theta$ by profile likelihood | Overdispersion grows faster than $\\mu$; you want a true likelihood (AIC, LRT) |\n| `QuasiPoissonFamily()` | $\\phi\\mu$ | $\\phi$ from Pearson residuals | Variance is proportional to the mean; you only need corrected standard errors |\n| `TweedieFamily()` | $\\phi\\mu^p$, $1<p<2$ | $\\phi$, optionally $p$ | Semicontinuous data with a point mass at zero (biomass, rainfall, cost); usable for counts, but it treats them as continuous |\n\nBecause quasi-likelihood is not a likelihood, quasi-Poisson has no AIC:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nprintln(\"Poisson AIC = \", round(aic(m_od_pois), digits = 1))\nprintln(\"NegBin  AIC = \", round(aic(m_od_nb), digits = 1))\nprintln(\"quasi-Poisson AIC = \", aic(m_od_qp), \"  (undefined — no likelihood)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPoisson AIC = 4729.5\nNegBin  AIC = 2716.3\nquasi-Poisson AIC = NaN  (undefined — no likelihood)\n```\n:::\n:::\n\n\n\n### What overdispersion costs you\n\nThe reason this matters is uncertainty, not the point estimate:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nse_p  = smooth_estimates(m_od_pois; n = 50)\nse_nb = smooth_estimates(m_od_nb;   n = 50)\nse_qp = smooth_estimates(m_od_qp;   n = 50)\n\nprintln(\"mean SE of ŝ(x):\")\nprintln(\"  Poisson       \", round(mean(se_p.se),  digits = 4))\nprintln(\"  NegBin        \", round(mean(se_nb.se), digits = 4),\n        \"   (\", round(mean(se_nb.se) / mean(se_p.se), digits = 2), \"× Poisson)\")\nprintln(\"  quasi-Poisson \", round(mean(se_qp.se), digits = 4),\n        \"   (\", round(mean(se_qp.se) / mean(se_p.se), digits = 2), \"× Poisson)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmean SE of ŝ(x):\n  Poisson       0.0501\n  NegBin        0.1083   (2.16× Poisson)\n  quasi-Poisson 0.131   (2.62× Poisson)\n```\n:::\n:::\n\n\n\nThe Poisson model understates the standard error of the smooth by a factor of\nmore than two. Confidence intervals built from it are far too narrow, and any\ntest of \"is this seasonal signal real?\" is correspondingly overconfident.\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\np_od = plot(se_p.covariates[:x], se_p.estimate .- mean(se_p.estimate);\n    ribbon = 2 .* se_p.se, fillalpha = 0.25, color = :steelblue,\n    label = \"Poisson ± 2SE\", linewidth = 2,\n    xlabel = \"x\", ylabel = \"log mean (centred)\",\n    title = \"Same fit, honest vs overconfident intervals\")\nplot!(p_od, se_nb.covariates[:x], se_nb.estimate .- mean(se_nb.estimate);\n    ribbon = 2 .* se_nb.se, fillalpha = 0.15, color = :darkorange,\n    label = \"NegBin ± 2SE\", linewidth = 2)\nplot!(p_od, se_p.covariates[:x], 0.9 .* sin.(2π .* se_p.covariates[:x]);\n    label = \"true f(x)\", linestyle = :dash, color = :red, linewidth = 2)\np_od\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](04_families_files/figure-commonmark/cell-31-output-1.svg){}\n:::\n:::\n\n\n\n## Rootograms — do the predicted counts match?\n\nDispersion statistics summarise the misfit in a single number. A **rootogram**\n(Kleiber & Zeileis, 2016) shows *where* in the count distribution it lives: for\neach count $k$ it compares how many observations equal $k$ with how many the\nfitted model expects, on a square-root scale so small frequencies stay visible.\n\nIn a **hanging** rootogram each bar hangs from the expected curve down by\n$\\sqrt{\\text{observed}}$. Bars that fail to reach zero mark counts the model\n**over**-predicts; bars crossing below zero mark counts it **under**-predicts.\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nrg_p  = rootogram(m_od_pois; max_count = 40)\nrg_nb = rootogram(m_od_nb;   max_count = 40)\n\nbot_p  = rg_p.sqrt_expected  .- rg_p.sqrt_observed\nbot_nb = rg_nb.sqrt_expected .- rg_nb.sqrt_observed\n\nrg_plot_p = bar(rg_p.count, rg_p.sqrt_observed; fillto = bot_p,\n    label = \"observed\", fillalpha = 0.6, color = :steelblue, linewidth = 0,\n    xlabel = \"count\", ylabel = \"√frequency\", title = \"Poisson\")\nplot!(rg_plot_p, rg_p.count, rg_p.sqrt_expected; label = \"expected\",\n    linewidth = 2, color = :red)\nhline!(rg_plot_p, [0]; color = :black, linestyle = :dash, label = false)\n\nrg_plot_nb = bar(rg_nb.count, rg_nb.sqrt_observed; fillto = bot_nb,\n    label = \"observed\", fillalpha = 0.6, color = :darkorange, linewidth = 0,\n    xlabel = \"count\", ylabel = \"√frequency\", title = \"Negative binomial\")\nplot!(rg_plot_nb, rg_nb.count, rg_nb.sqrt_expected; label = \"expected\",\n    linewidth = 2, color = :red)\nhline!(rg_plot_nb, [0]; color = :black, linestyle = :dash, label = false)\n\nplot(rg_plot_p, rg_plot_nb; layout = (1, 2), size = (1000, 380))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](04_families_files/figure-commonmark/cell-32-output-1.svg){}\n:::\n:::\n\n\n\nThe zero cell makes the diagnosis immediate:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nprintln(\"observations equal to 0:  \", Int(rg_p.observed[1]))\nprintln(\"  expected under Poisson: \", round(rg_p.expected[1], digits = 1))\nprintln(\"  expected under NegBin:  \", round(rg_nb.expected[1], digits = 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nobservations equal to 0:  15\n  expected under Poisson: 1.4\n  expected under NegBin:  16.0\n```\n:::\n:::\n\n\n\nThe Poisson model expects barely one zero and 15 occur; the negative binomial\nexpects 16. The Poisson rootogram shows the classic overdispersion signature —\ntoo few predicted counts in both tails, too many in the middle — while the\nnegative binomial bars sit close to zero throughout.\n\n::: {.callout-note}\n`rootogram` is defined for count families only (`Poisson`,\n`QuasiPoissonFamily`, `NegBinFamily`); calling it on a Tweedie or Gaussian fit\nraises an `ArgumentError`, since there is no probability mass function to\ncompare against.\n:::\n\n## Comparison\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nprintln(\"Family        EDF      Dev.Expl(%)   Scale\")\nprintln(\"─\" ^ 55)\nfor (name, m) in [(\"Poisson\", m_pois), (\"Binomial\", m_bin), (\"Gamma\", m_gam)]\n    e = round(edf(m)[1]; digits = 2)\n    de = round(GAM.deviance_explained(m) * 100; digits = 1)\n    sc = round(m.scale; digits = 4)\n    println(\"$(rpad(name, 14))$(lpad(string(e), 6))  $(lpad(string(de), 12))  $(lpad(string(sc), 8))\")\nend\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFamily        EDF      Dev.Expl(%)   Scale\n───────────────────────────────────────────────────────\nPoisson         7.98          76.4       1.0\nBinomial        4.98          25.5       1.0\nGamma           6.18          41.5    0.1811\n```\n:::\n:::\n\n\n\n### All smooth estimates together\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nplot(p1, p3, p5; layout = (1, 3), size = (1000, 350))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](04_families_files/figure-commonmark/cell-35-output-1.svg){}\n:::\n:::\n\n\n\n## Summary\n\nIn this vignette we:\n\n1. Simulated count data and fitted a **Poisson GAM** with a log link\n2. Simulated binary data and fitted a **Binomial GAM** with a logit link\n3. Simulated positive continuous data and fitted a **Gamma GAM** with a log link\n4. Examined smooth estimates and deviance residuals for each family\n5. Compared EDF and deviance explained across families\n6. Used an **offset** (`offset = log.(pop)`) to model incidence *rates* rather\n   than counts, and saw why that beats both a $\\log(\\text{pop})$ covariate and a\n   Gaussian model of $y/\\text{pop}$\n7. Diagnosed **overdispersion** with the Pearson dispersion statistic and\n   handled it with `NegBinFamily`, `QuasiPoissonFamily` and `TweedieFamily`,\n   finding that the Poisson standard errors were more than 2× too small\n8. Used **rootograms** to see exactly which counts the Poisson model got wrong\n\nEach family uses a different link function to map the linear predictor to the mean of the response distribution, but the smooth estimation machinery is the same.\n\n## References\n\nKleiber, C. and Zeileis, A. (2016). Visualizing count data regressions using\nrootograms. *The American Statistician* **70**(3), 296–303.\n\n",
    "supporting": [
      "04_families_files"
    ],
    "filters": [],
    "includes": {}
  }
}